apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskflow.fullname" . }}-api-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app: api
data:
  NODE_ENV: {{ .Values.api.env.nodeEnv | quote }}
  PORT: {{ .Values.api.env.port | quote }}
  MONGO_URI: {{ .Values.api.env.mongoUri | quote }}
  JWT_EXPIRES_IN: {{ .Values.api.env.jwtExpiresIn | quote }}
  ALLOWED_ORIGINS: {{ .Values.api.env.allowedOrigins | quote }}
