apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-api-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app: api
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.env.jwtSecret | quote }}
  MONGO_URI: {{ .Values.api.env.mongoUri | quote }}
