apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
    app: mongo
