{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskflow.fullname" . }}-web
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app: web
spec:
  {{- if .Values.web.pdb.minAvailable }}
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.web.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" . | nindent 6 }}
      app: web
{{- end }}
