apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app: web
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
    app: web
  type: ClusterIP
