{{- if and .Values.ingress.enabled .Values.web.deployments.canary.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "taskflow.fullname" . }}-web-ingress-canary
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: {{ .Values.web.deployments.canary.weight | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-canary
                port:
                  number: 80
{{- end }}
